package com.compose.myapplication;

/**
 * A class to hold the static data used across the application.
 *
 * @author Rick
 */
public class Data {
    public static int TRACK_01 = R.raw.track;
    public Artwork[] artworks = {
            new Artwork("Yuki_Nagato", "HitsuHere", "http://hitsuhere.deviantart.com/", R.drawable.image00),
            new Artwork("Adventure_Time", "HitsuHere", "http://hitsuhere.deviantart.com/", R.drawable.image01),
            new Artwork("Stocking_D_City_Rock", "HitsuHere", "http://hitsuhere.deviantart.com/", R.drawable.image02),
            new Artwork("Spring_Forest", "Even_Skaranger_Art", "http://evenskarangerart.deviantart.com/", R.drawable.image03),
            new Artwork("Madikken_in_the_shade", "Even_Skaranger_Art", "http://evenskarangerart.deviantart.com/", R.drawable.image04),
            new Artwork("Ruins_from_the_Past", "Even_Skaranger_Art", "http://evenskarangerart.deviantart.com/", R.drawable.image05),
            new Artwork("Lifespawn", "Ryuka", "http://ryuka-hime.deviantart.com/", R.drawable.image06),
            new Artwork("Animal_Heroes ", "Ryuka", "http://ryuka-hime.deviantart.com/", R.drawable.image07),
            new Artwork("Summertime_is_waterfight_time! ", "Ryuka", "http://ryuka-hime.deviantart.com/", R.drawable.image08),
            new Artwork("Ladylike Gun", "Ryuka", "http://ryuka-hime.deviantart.com/", R.drawable.image09),
            new Artwork("Memories", "Ryuka", "http://ryuka-hime.deviantart.com/", R.drawable.image10),
            new Artwork("The_Trio", "scrson", "http://scrson.deviantart.com/", R.drawable.image11),
            new Artwork("Kitsunes_Camera", "Miss_Creativity96", "http://miss-creativity96.deviantart.com/", R.drawable.image12),
            new Artwork("Nyan_Kitsune", "Miss_Creativity96", "http://miss-creativity96.deviantart.com/", R.drawable.image13),
            new Artwork("Happy_Pinkie_Pie", "Miss_Creativity96", "http://miss-creativity96.deviantart.com/", R.drawable.image14),
            new Artwork("Yuichiro_Hyakuya", "OtakuSaz", "http://otakusaz.deviantart.com/", R.drawable.image15),
            new Artwork("Nanako_Dojima", "OtakuSaz", "http://otakusaz.deviantart.com/", R.drawable.image16),
            new Artwork("Ail_and_An_Sailor_Moon_R", "Nuciferyne", "http://nuciferyne.deviantart.com/", R.drawable.image17),
            new Artwork("Gossip_on_the_Beach", "Nuciferyne", "http://nuciferyne.deviantart.com/", R.drawable.image18),
            new Artwork("Lilia", "pin100", "http://pin100.deviantart.com/", R.drawable.image19),
            new Artwork("Abel_Nightroad", "pin100", "http://pin100.deviantart.com/", R.drawable.image20),
            new Artwork("Yuki", "pin100", "http://pin100.deviantart.com/", R.drawable.image21),
            new Artwork("Van_Fanel", "Dennis_Menese", "http://clearmirror-stillh2o.deviantart.com/", R.drawable.image22),
            new Artwork("KIRA_and_ZERO_Men_of_Justice", "Dennis_Menese", "http://clearmirror-stillh2o.deviantart.com/", R.drawable.image23),
            new Artwork("World_Martial_Arts_Tournament", "Dennis_Menese", "http://clearmirror-stillh2o.deviantart.com/", R.drawable.image24),
            new Artwork("Food_Wars", "Shumi", "http://shumijin.deviantart.com/", R.drawable.image25),
            new Artwork("Haikyuu", "Shumi", "http://shumijin.deviantart.com/", R.drawable.image26),
            new Artwork("Tokyo_Ghoul", "Shumi", "http://shumijin.deviantart.com/", R.drawable.image27),
            new Artwork("D_Gray_Man", "Shumi", "http://shumijin.deviantart.com/", R.drawable.image28),
            new Artwork("Cancer", "eschellan", "http://eschellan.deviantart.com/", R.drawable.image29),
            new Artwork("Len", "eschellan", "http://eschellan.deviantart.com/", R.drawable.image30),
            new Artwork("Obon_Night_Free!)", "megumonster", "http://megumonster.deviantart.com/", R.drawable.image31),
            new Artwork("It_s_a_Day_Off_Kekkai_Sensen)", "megumonster", "http://megumonster.deviantart.com/", R.drawable.image32),
            new Artwork("My_Wakagashira_Kuroko_no_Basuke)", "megumonster", "http://megumonster.deviantart.com/", R.drawable.image33),
            new Artwork("In_the_rain", "megumonster", "http://megumonster.deviantart.com/", R.drawable.image34),
            new Artwork("Courage_Test_crossover", "megumonster", "http://megumonster.deviantart.com/", R.drawable.image35),
            new Artwork("The_Rain_Lady", "yammybonbon", "http://yammybonbon.deviantart.com/", R.drawable.image36),
            new Artwork("Sinon", "yammybonbon", "http://yammybonbon.deviantart.com/", R.drawable.image37),
            new Artwork("The Wizard Howl", "yammybonbon", "http://yammybonbon.deviantart.com/", R.drawable.image38),
            new Artwork("Kago_to_Torii", "Nuei", "http://nuei.deviantart.com/", R.drawable.image39),
            new Artwork("Red_Blossom", "Nuei", "http://nuei.deviantart.com/", R.drawable.image40),
            new Artwork("Sinon", "fuanteinaa", "http://fuanteinaa.deviantart.com/", R.drawable.image41),
            new Artwork("wonderful", "fuanteinaa", "http://fuanteinaa.deviantart.com/", R.drawable.image42),
            new Artwork("Ignorance_is_bliss", "Cora_Rm", "http://cora-rosemountain.deviantart.com/", R.drawable.image43),
            new Artwork("The_best_decoy", "Cora_Rm", "http://cora-rosemountain.deviantart.com/", R.drawable.image44),
            new Artwork("Madoka_x_Himari", "Eri_chan_45", "http://eri-chan45.deviantart.com/", R.drawable.image45),
            new Artwork("Shigatsu_wa_kimi_no_uso", "Eri_chan_45", "http://eri-chan45.deviantart.com/", R.drawable.image46),
            new Artwork("The_sky_at_worlds_end", "Eri_chan_45", "http://eri-chan45.deviantart.com/", R.drawable.image47),
            new Artwork("Illusion", "Rumi_Kuu", "http://rumi-kuu.deviantart.com", R.drawable.image48),
            new Artwork("Come_Along_Our_Journey", "Rumi_Kuu", "http://rumi-kuu.deviantart.com", R.drawable.image49),
            new Artwork("Genesis", "Rumi_Kuu", "http://rumi-kuu.deviantart.com", R.drawable.image50),
            new Artwork("Heavens_wheel", "Dakiarts", "http://dakiarts.deviantart.com", R.drawable.image51),
            new Artwork("Flying_freedom ", "Dakiarts", "http://dakiarts.deviantart.com", R.drawable.image52),
            new Artwork("Fairy_Pond", "Dakiarts", "http://dakiarts.deviantart.com", R.drawable.image53),
            new Artwork("Cardcaptor_Sakura", "mukimillia", "http://mukimillia.deviantart.com", R.drawable.image54),
            new Artwork("Amanecer", "mukimillia", "http://mukimillia.deviantart.com", R.drawable.image55),
            new Artwork("Youre_a_kid_youre_a_squid", "mukimillia", "http://mukimillia.deviantart.com", R.drawable.image56),
            new Artwork("Centerstage_1_Elizabeth", "Dane_Celestia", "http://mukimillia.deviantart.com", R.drawable.image57),
            new Artwork("Kill_La_Kill", "youmistsukisaya", "http://youmistsukisaya.deviantart.com/", R.drawable.image58),
            new Artwork("Reiner_Rubin", "youmistsukisaya", "http://youmistsukisaya.deviantart.com/", R.drawable.image62),
            new Artwork("Schnee_Kristall", "youmistsukisaya", "http://youmistsukisaya.deviantart.com/", R.drawable.image60),
            new Artwork("water_lily", "youmistsukisaya", "http://youmistsukisaya.deviantart.com/", R.drawable.image62),
            new Artwork("yangyangXD_s_Foxy", "Ailurophile-Chan", "http://youmistsukisaya.deviantart.com/", R.drawable.image62),
            new Artwork("Mikasa", "Nick-Ian", "http://nick-ian.deviantart.com", R.drawable.image63),
            new Artwork("Psycho_Pass", "Nick-Ian", "http://nick-ian.deviantart.com", R.drawable.image64),
            new Artwork("Dragon_Force_Wendy", "Nick-Ian", "http://nick-ian.deviantart.com", R.drawable.image65),
            new Artwork("Titans", "Nick-Ian", "http://nick-ian.deviantart.com", R.drawable.image66),
            new Artwork("Shinha", "Nick-Ian", "http://nick-ian.deviantart.com", R.drawable.image67),
            new Artwork("Bottle Miku", "Dakiarts", "http://dakiarts.deviantart.com", R.drawable.image68),
            new Artwork("Kisaragi_Momo", "dimdimensions", "http://dimdimensions.deviantart.com", R.drawable.image69),
            new Artwork("No_Game_No_Life_Shiro", "dimdimensions", "http://dimdimensions.deviantart.com", R.drawable.image70),
            new Artwork("My_Boyfriend_Is_A_Star", "dimdimensions", "http://dimdimensions.deviantart.com", R.drawable.image71),
            new Artwork("Onward", "the10s", "http://the10s.deviantart.com", R.drawable.image72),
            new Artwork("All_Aboard", "the10s", "http://the10s.deviantart.com", R.drawable.image73),
            new Artwork("From_up_on_poppy_hill", "the10s", "http://the10s.deviantart.com", R.drawable.image74),
            new Artwork("Marie_Skull_girls", "MurLovely", "http://murlovely.deviantart.com", R.drawable.image75),
            new Artwork("Cyan_Show_by_Rock", "MurLovely", "http://murlovely.deviantart.com", R.drawable.image76),
            new Artwork("Chuchu_Show_by_Rock", "MurLovely", "http://murlovely.deviantart.com", R.drawable.image77),
            new Artwork("nanami_maid", "MurLovely", "http://murlovely.deviantart.com", R.drawable.image78),
            new Artwork("a_cute_bikini_ikaros", "MurLovely", "http://murlovely.deviantart.com", R.drawable.image79),
            new Artwork("five_nights_at_freddys", "majesticfuckingeagle", "http://majesticfuckingeagle.deviantart.com", R.drawable.image80),
            new Artwork("untitled", "Kay", "http://ekaterina-sudsukie.deviantart.com/", R.drawable.image81),
            new Artwork("owari_no_seraph", "Kay", "http://ekaterina-sudsukie.deviantart.com/", R.drawable.image82),
            new Artwork("fairy_tale", "Kay", "http://ekaterina-sudsukie.deviantart.com/", R.drawable.image83),
            new Artwork("Hina_Fukami_Glasslip", "hsm64", "http://hsm64.deviantart.com/", R.drawable.image84),
            new Artwork("Kill_them_all", "hsm64", "http://hsm64.deviantart.com/", R.drawable.image85),
            new Artwork("Spike", "hsm64", "http://hsm64.deviantart.com/", R.drawable.image86),
            new Artwork("Makise_Kurisu", "Dravici_Andrei", "http://draviciandrei.deviantart.com/", R.drawable.image87),
            new Artwork("Kaori_Miyazono", "Dravici_Andrei", "http://draviciandrei.deviantart.com/", R.drawable.image88),
            new Artwork("Tetsuya_Kutoko", "Dravici_Andrei", "http://draviciandrei.deviantart.com/", R.drawable.image89),
            new Artwork("Saber_Lily", "Dravici_Andrei", "http://draviciandrei.deviantart.com/", R.drawable.image90),
            new Artwork("Kosaki_Onodera_Nisekoi", "Starsilvery", "http://starsilvery.deviantart.com/", R.drawable.image91),
            new Artwork("Chitoge_Kirisaki_Nisekoi", "Starsilvery", "http://starsilvery.deviantart.com/", R.drawable.image92),
            new Artwork("elsa", "JESSE", "http://yiichan.deviantart.com/", R.drawable.image93),
            new Artwork("missfortune", "JESSE", "http://yiichan.deviantart.com/", R.drawable.image94),
            new Artwork("Chibi_Hestia", "Spaca_Scaleno", "http://spaca.deviantart.com", R.drawable.image95),
            new Artwork("Magic_Girls_Elesisand_Edel", "Spaca_Scaleno", "http://spaca.deviantart.com", R.drawable.image96),
            new Artwork("manaka", "Emi_Liu", "http://emi-liu.deviantart.com", R.drawable.image97),
            new Artwork("bottle_miku", "Emi_Liu", "http://emi-liu.deviantart.com", R.drawable.image98),
            new Artwork("junko_enoshima", "Emi_Liu", "http://emi-liu.deviantart.com", R.drawable.image99),
            new Artwork("maki", "Emi_Liu", "http://emi-liu.deviantart.com", R.drawable.image100),
            new Artwork("Kiki", "jubilri", "http://jubilri.deviantart.com/", R.drawable.image101),
            new Artwork("Homura", "jubilri", "http://jubilri.deviantart.com/", R.drawable.image102),
            new Artwork("Thunder", "DistructiveMusic", "http://distructivemusic.deviantart.com/", R.drawable.image103),
            new Artwork("Titan", "DistructiveMusic", "http://distructivemusic.deviantart.com/", R.drawable.image104),
            new Artwork("Hanayamata", "Artemisumi", "http://distructivemusic.deviantart.com/", R.drawable.image105),
            new Artwork("Rachel_vs_Morrigan", "Artemisumi", "http://distructivemusic.deviantart.com/", R.drawable.image106),
            new Artwork("miyoko", "AkaneYurika", "http://akaneyurika.deviantart.com", R.drawable.image107),
            new Artwork("sayanara_miyoko", "AkaneYurika", "http://akaneyurika.deviantart.com", R.drawable.image108),
            new Artwork("awatar", "AkaneYurika", "http://akaneyurika.deviantart.com", R.drawable.image109),
            new Artwork("Cyber_Ene", "Cloudkourin", "http://cloudkourin.deviantart.com/", R.drawable.image110),
            new Artwork("No_Game_No_Life", "Cloudkourin", "http://cloudkourin.deviantart.com/", R.drawable.image111),
            new Artwork("Childhood_s_End", "Cloudkourin", "http://cloudkourin.deviantart.com/", R.drawable.image112),
            new Artwork("Jafar", "Rikuross", "http://rikuross.deviantart.com/", R.drawable.image113),
            new Artwork("Our_Home", "Gavryll", "http://gavryll.deviantart.com/", R.drawable.image114),
            new Artwork("EcaxDigimon", "Ragha_Rakita", "http://ragha-rakita.deviantart.com/", R.drawable.image115),
            new Artwork("Chitoge-Nisekoi", "Ragha_Rakita", "http://ragha-rakita.deviantart.com/", R.drawable.image116),
            new Artwork("Flaga_Haimura_Moroha", "Ragha_Rakita", "http://ragha-rakita.deviantart.com/", R.drawable.image117),
            new Artwork("Isla_Plastic_Memories", "Ragha_Rakita", "http://ragha-rakita.deviantart.com/", R.drawable.image118),
            new Artwork("chibi_miku", "mikuandmord", "http://mikuandmord.deviantart.com/", R.drawable.image119),
            new Artwork("black_rock_shooter", "mikuandmord", "http://mikuandmord.deviantart.com/", R.drawable.image120),
            new Artwork("untitled", "famyuchii", "http://famyuchii.deviantart.com/", R.drawable.image121),
            new Artwork("Star_Butterfly_Rainbow_Splash", "AyaHimeTenshi", "http://ayahimetenshi.deviantart.com/", R.drawable.image122),
            new Artwork("Smile", "Misutore01", "http://misutore01.deviantart.com/", R.drawable.image123),
            new Artwork("Minato112", "Misutore01", "http://misutore01.deviantart.com/", R.drawable.image124),
            new Artwork("TORI_Whats_The_Matter_Pikachu", "GreenIbr", "http://misutore01.deviantart.com/", R.drawable.image125),
            new Artwork("if_i_were_20_years_younger_i_d_wear_you", "CandideKun", "http://candide1337.deviantart.com/", R.drawable.image126),
            new Artwork("Nami", "Rozemira", "http://rozemira.deviantart.com/", R.drawable.image127),
            new Artwork("Fun_and_Spells_with_Lux", "Rozemira", "http://rozemira.deviantart.com/", R.drawable.image128),
            new Artwork("Atelier Meruru", "Yoneyu", "http://yoneyu.deviantart.com/", R.drawable.image129),
            new Artwork("Kanato", " BonBonPoupee", " https://www.facebook.com/BonBonPoupeeArt", R.drawable.image130),
            new Artwork("Dreaming Mary", " BonBonPoupee", " https://www.facebook.com/BonBonPoupeeArt", R.drawable.image131),
            new Artwork("Aya", " BonBonPoupee", " https://www.facebook.com/BonBonPoupeeArt", R.drawable.image132),
            new Artwork("Yumeo Ochida", "M.Milles.Mark", "http://hananueaoko.deviantart.com/", R.drawable.image133),
            new Artwork("Slayer girl", "Lora", "http://omikuy.deviantart.com/", R.drawable.image134),
            new Artwork("Radiant Spirit", "Destiny Sword", "http://destinysword.deviantart.com/", R.drawable.image135),
            new Artwork("Open Heart", "Destiny Sword", "http://destinysword.deviantart.com/", R.drawable.image136),
            new Artwork("AKB0048 Makoto Yokomizo", "PikaSetsuna", "http://pikasetsuna.deviantart.com/", R.drawable.image137),
            new Artwork("Badass Girl", "Ferensa", "http://the-sweetshop-fc.deviantart.com/", R.drawable.image138),
            new Artwork("Angel", "Shimozuku", "http://shimozuku.deviantart.com/", R.drawable.image139),
            new Artwork("Magical", "BluePikachuSenpai", "http://bluepikachusenpai.deviantart.com/", R.drawable.image140),
            new Artwork("yui k_on", "Nikkon Heguy", "http://nikkonh.deviantart.com/", R.drawable.image141),
    };
}